# Generated by Django 3.2 on 2022-04-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_personfilmwork_film_work_creation_date_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='file_path'),
        ),
    ]
