# Generated by Django 3.2 on 2022-04-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_filmwork_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='file_path'),
        ),
    ]
